Align To Amp
frc2609/Crescendo-2024 pull request #52
Opened 2024-03-03 23:30 UTC by UserC2

Closes #42 
Closes #5 

Tested by WhyNot180 & UserC2 in simulation.

2024-03-05 20:47 UTC, WhyNot180 requested changes

2024-03-05 20:47 UTC, WhyNot180 commented on src/main/java/frc/robot/commands/AprilTagTrackDrive.java
This still needs a check for alliance colour.

2024-03-09 17:00 UTC, UserC2 commented on src/main/java/frc/robot/subsystems/Limelight.java
AprilTagTrackDrive target rotation should be in AprilTagTrackDrive, NOT in Limelight.

2024-03-09 17:00 UTC, UserC2 commented on src/main/java/frc/robot/subsystems/Limelight.java
Less magic necessary (check whether this angle is actually correct)

2024-03-09 17:00 UTC, UserC2 commented on src/main/java/frc/robot/commands/AprilTagTrackDrive.java
File good, magic bad.

2024-03-09 20:00 UTC, merged